version: '3.4'

services:
  impactanalytics2021:
    image: impactanalytics2021
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
